% ALGORITHM: random test case generation
% uniformly random number on the input range for each input
%
% PARAMS:
%     Input:
%     - model: the model will be run in this experiment
%     - input_names: the name of inputs
%     - input_ranges: the range of inputs
%     - categorical: index of categorical inputs
%     - opt: algorithm options
%     - sim_opt: simulation options
%
%     Output:
%     - score: the mutation score of this run

function score = random_algo(...
    model,...
    input_names,...
    input_ranges,...
    categorical,...
    opt,...
    sim_opt...
)
    % call gen_suite function to randomly generate test suite
    [tv, ~] = gen_suite_random_algo(...
        input_names,...
        input_ranges,...
        categorical,...
        opt...
    );
    
    % check the mutation score on randomly generated test suite
    score = mutation_check(tv, model, sim_opt, opt, input_ranges);
    
    